manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('manager_welcome.urls')),
    path('app/', include('manager_app.urls')),
    path('add/', include('manager_add.urls')),
    path('edit/', include('manager_edit.urls')),
    path('authorization/', include('manager_login.urls')),
    path('currency/', include('currency_exchange.urls')),
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager_add/urls.py
from django.urls import path, include
from . import views

app_name = 'manager_add'

urlpatterns = [
    # path('', views.index, name='index'),
    path('items/add_item/', views.add_item, name='add-item'),
    path('orders/add_order/', views.add_order, name='add-order'),
    path('reservations/add_reservation/', views.add_reservation, name='add-reservation'),
    # path('users/add_user/', views.add_user, name='add-user'),
    # path('orders/add_order/', views.add_order, name='add-order'),
    # path('reservations/add_reservation/', views.add_reservation, name='add-reservation'),

    # path('orders/', views.orders, name='orders'),
    # path('reservations/', views.reservations, name='reservations'),
    # path('users/', views.users, name='users'),
    # path('analytics/', views.analytics, name='analytics'),
    # path('convert/<str:currency>/', views.convert_currency, name='convert_currency'),
]

manager_app/urls.py
from django.urls import path
from . import views

app_name='manager_app'

urlpatterns = [
    path('analytics_admin/', views.analytics_for_admin, name='analytics-for-admin'),
    path('analytics_user/', views.analytics_for_user, name='analytics-for-user'),
    # path('', views.analytics, name='analytics'),
    # path('api/order_sums_by_month/', order_sums_by_month, name='order_sums_by_month'),
    path('items/', views.items, name='items'),
    # path('update_item/<int:shoes_id>/', views.update_item, name='update-item'),
    path('det/<int:id>/', views.items_detailed_view, name='items-photos'),
    path('items/delete/<int:shoes_id>/', views.items_delete, name='items-delete'),
    # path('edit/<int:id>/', views.items_form_edit, name='items-form-edit'),
    path('users/', views.users, name='users'),
    path('users_toggle_status/<int:user_id>/', views.users_toggle_status, name='users_toggle_status'),
    path('users/delete/<int:user_id>/', views.users_delete, name='users-delete'),
    # path('users/update_user/<int:user_id>/', views.update_user, name='update-user'),
    path('orders/', views.orders, name='orders'),
    path('orders-detail/<int:id>/', views.orders_detailed_view, name='orders-detail'),
    path('orders/delete/<int:order_id>/', views.orders_delete, name='orders-delete'),
    # path('orders/update_order/<int:order_id>/', views.update_order, name='update-order'),
    # path("order-sum/", views.order_sum_view, name="order-sum"),
    path('reservations/', views.reservations, name='reservations'),
    path('reservations/delete/<int:reservation_id>/', views.reservations_delete, name='reservations-delete'),
    # path('reservations/update_reservation/<int:reservation_id>/', views.update_reservation, name='update-reservation'),
    # path('convert/<str:currency>/', views.convert_currency, name='convert_currency'),
]
 

manager_edit/urls.py
from django.urls import path, include
from . import views

app_name = 'manager_edit'

urlpatterns = [
    # path('', views.index, name='index'),
    path('update_item/<int:shoes_id>/', views.update_item, name='update-item'),
    path('users/update_user/<int:user_id>/', views.update_user, name='update-user'),
    path('orders/update_order/<int:order_id>/', views.update_order, name='update-order'),
    path('reservations/update_reservation/<int:reservation_id>/', views.update_reservation, name='update-reservation'),

    # path('orders/', views.orders, name='orders'),
    # path('reservations/', views.reservations, name='reservations'),
    # path('users/', views.users, name='users'),
    # path('analytics/', views.analytics, name='analytics'),
    # path('convert/<str:currency>/', views.convert_currency, name='convert_currency'),
]

manager_app/models.py
from django.db import models
from enum import Enum
from datetime import datetime, timedelta
from django.db.models import Sum
from django.utils import timezone
# from django.contrib.postgres.fields import ArrayField

class Order_status(Enum):
    accepted = 'accepted'
    paid = 'paid'
    in_processing = 'in processing'
    shipped = 'shipped'
    delivered = 'delivered'
    paid_to_dropper = 'paid to dropper'  
    
class User_role(Enum):
    administartor = 'administartor'
    user = 'user'
       
# class ShoeSize(models.Model):
#     size = models.IntegerField()  
     
class Shoes(models.Model):
    id_shoes = models.AutoField(primary_key=True, unique=True)
    sh_name = models.CharField(max_length=255)
    sh_model = models.CharField(max_length=255)
    sh_size = models.IntegerField(null=False, default=38)
    sh_color = models.CharField(max_length=255)
    sh_manufacturer = models.CharField(max_length=255, blank=True, null=True)
    sh_count = models.IntegerField(null=False, default=1)
    sh_price = models.DecimalField(max_digits=10, decimal_places=2)
    sh_image = models.ImageField(blank=False, upload_to='images/')  # Якщо використано bytea, можна використати BinaryField
    
    class Meta:
        db_table = 'shoes'

# class ShoesImages(models.Model):
#     item = models.ForeignKey(Shoes, related_name='images', on_delete=models.CASCADE)
#     images = models.FileField(upload_to='images/')
#     # is_first = models.BooleanField(default=False)
#     # is_second = models.BooleanField(default=False)
    
#     def __str__(self):
#         return self.item.sh_name
    
class Users(models.Model):
    id_user = models.IntegerField(primary_key=True)
    u_username = models.CharField(max_length=255)
    u_name = models.CharField(max_length=255)
    u_surname = models.CharField(max_length=255)
    u_email = models.CharField(max_length=255, blank=True, null=True)
    u_phone = models.CharField(max_length=13)
    u_status = models.BooleanField(default=False)
    u_role = models.CharField(max_length=45,default=User_role.user.name, choices=[(user_role.value, user_role.name) for user_role in User_role])
    
    class Meta:
        db_table = 'users'
    
class Orders(models.Model):
    id_order = models.AutoField(primary_key=True)
    o_shoes = models.ForeignKey(Shoes, on_delete=models.CASCADE, db_column='o_shoes')
    o_count = models.IntegerField(null=False, default=1)
    o_sum = models.DecimalField(max_digits=10, decimal_places=2)
    o_recipient = models.CharField(max_length=45, null=False, default='Name,Surname')
    o_address = models.CharField(max_length=100, null=False, default='Address')
    o_comment=models.CharField(max_length=100, null=True)
    o_status = models.CharField(max_length=45, default=Order_status.accepted.value, choices=[(status.value, status.name) for status in Order_status])    
    o_user = models.ForeignKey(Users, on_delete=models.CASCADE, null = True, db_column='o_user')
    o_date_created = models.DateTimeField(default=timezone.now)
    class Meta:
        db_table = 'orders'

    @classmethod
    def calculate_total_sum(cls):
        return cls.objects.aggregate(total_sum=models.Sum('o_sum'))['total_sum'] or 0

    @classmethod
    def calculate_average_sum(cls):
        total_sum = cls.calculate_total_sum()
        total_orders = cls.objects.count()
        return total_sum / total_orders if total_orders != 0 else 0

    @classmethod
    def find_max_sum(cls):
        return cls.objects.aggregate(max_sum=models.Max('o_sum'))['max_sum'] or 0

    @classmethod
    def find_min_sum(cls):
        return cls.objects.aggregate(min_sum=models.Min('o_sum'))['min_sum'] or 0

    @classmethod
    def calculate_total_sum_for_current_month(cls):
        # Get the current year and month
        current_year = timezone.now().year
        current_month = timezone.now().month

        # Filter orders for the current month
        orders_for_current_month = cls.objects.filter(
            o_date_created__year=current_year,
            o_date_created__month=current_month
        )

        # Calculate the total sum for the current month
        total_sum_for_current_month = orders_for_current_month.aggregate(total_sum=Sum('o_sum'))['total_sum']

        return total_sum_for_current_month or 0  # Return 0 if no orders found for the current month       

class Reservations(models.Model):
    id_reservation = models.AutoField(primary_key=True)
    r_shoes = models.ForeignKey(Shoes, on_delete=models.CASCADE, db_column='r_shoes')
    r_count = models.IntegerField(null=False, default=1)
    r_start_date = models.DateTimeField(default=timezone.now)
    r_end_date = models.DateTimeField(default=timezone.now() + timedelta(hours=3))
    r_user = models.ForeignKey(Users, on_delete=models.CASCADE, db_column='r_user')

    class Meta:
        db_table = 'reservations'
        
        

manager_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from manager_app.models import *
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib import messages
import plotly.express as px
from datetime import datetime,timedelta

def items(request):
    data = Shoes.objects.all()
    return render(request, 'manager_app/items.html', {'data': data})


def items_detailed_view(request, id):
    item = get_object_or_404(Shoes, id_shoes=id)
    # Either render only the modal content, or a full standalone page
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        template_name = 'manager_app/items.html'
    else:
        template_name = 'manager_app/items.html'
    return render(request, template_name, {'item':item})
    

    
def items_delete(request, shoes_id):
    item = get_object_or_404(Shoes, id_shoes = shoes_id)

    if request.method == 'POST':
        item.delete()
        return redirect('manager_app:items')

    return redirect('manager_app:items')

def users(request):
    # return render(request, 'users.html')
    data = Users.objects.all()
    return render(request, 'manager_app/users.html', {'data': data})

def users_toggle_status(request, user_id):
    user = get_object_or_404(Users, id_user=user_id)
    if user.u_status != True:
       user.u_status = True
    else:
        redirect('manager_app:users')
    user.save()
    return redirect('manager_app:users')

def users_delete(request, user_id):
    user = get_object_or_404(Users, id_user = user_id)

    if request.method == 'POST':
        user.delete()
        return redirect('manager_app:users')

    return redirect('manager_app:users')

    
def orders(request):
    # return render(request, 'orders.html')
    data = Orders.objects.all()
    for item in data:
        item.order_sum = item.o_count * item.o_shoes.sh_price
    order_status = [(status.value, status.name) for status in Order_status]
    return render(request, 'manager_app/orders.html', {'data': data, 'order_status': order_status})

def orders_detailed_view(request, id):
    item = get_object_or_404(Orders, id_order=id)
    # photos = ShoesImages.objects.filter(item=item)
    # Either render only the modal content, or a full standalone page
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        template_name = 'manager_app/orders.html'
    else:
        template_name = 'manager_app/orders.html'
    return render(request, template_name, {
        'item':item,  
    })
   
def orders_delete(request, order_id):
    order = get_object_or_404(Orders, id_order = order_id)

    if request.method == 'POST':
        order.delete()
        return redirect('manager_app:orders')

    return redirect('manager_app:orders')


# def order_sum_view(request):
    # total_sum = Orders.objects.aggregate(total_sum=Sum(F('o_count') * F('o_shoes__sh_price')))
    # order_sum = total_sum['total_sum'] if total_sum['total_sum'] else 0
    # return render(request, 'orders.html', {'order_sum': order_sum})


def reservations(request):
    # return render(request, 'orders.html')
    now = timezone.now()
    Reservations.objects.filter(r_end_date__lt=now).delete()

    data = Reservations.objects.all()
    return render(request, 'manager_app/reservations.html', {'data': data})

def reservations_delete(request, reservation_id):
    reservation = get_object_or_404(Reservations, id_reservation = reservation_id)

    if request.method == 'POST':
        reservation.delete()
        return redirect('manager_app:reservations')

    return redirect('manager_app:reservations')

def update_reservation(request, reservation_id):
    # Отримуємо об'єкт Shoes за його ідентифікатором
    reservation = get_object_or_404(Reservations, id_reservation=reservation_id)
    
    shoes_list = Shoes.objects.all()
    if request.method == 'POST':
        r_shoes_id = request.POST.get('r_shoes')
        try:
            shoes = Shoes.objects.get(id_shoes=r_shoes_id)
        except Shoes.DoesNotExist:
            error_message = "Взуття з вказаним ідентифікатором не існує"
            return render(request, 'manager_app/reservations-edit.html', {'reservation': reservation, 'error_message': error_message})
        
        # Перевіряємо, чи кількість взуття більше 0
        if shoes.sh_count > 0:
            # Отримуємо кількість, яку користувач ввів
            r_count = int(request.POST.get('r_count', 0))
            
            # Перевіряємо, чи введена кількість менше або дорівнює кількості в наявності
            if r_count <= shoes.sh_count:
                reservation.r_shoes = shoes
                reservation.r_count = r_count
                reservation.save()
                return redirect('manager_app:reservations')
            else:
                error_message = "Вибрана кількість перевищує кількість в наявності"
                return render(request, 'manager_app/reservations-edit.html', {'reservation': reservation, 'shoes_list': shoes_list, 'error_message': error_message})
        else:
            error_message = "Вибране взуття відсутнє в наявності"
            return render(request, 'manager_app/reservations-edit.html', {'reservation': reservation,'shoes_list': shoes_list, 'error_message': error_message})
    else:
        return render(request, 'manager_app/reservations-edit.html', {'reservation': reservation, 'shoes_list': shoes_list})   
   
   
def analytics_for_admin(request):
    total_sum = Orders.calculate_total_sum()
    average_sum = Orders.calculate_average_sum()
    max_sum = Orders.find_max_sum()
    min_sum = Orders.find_min_sum()

    current_month = datetime.now().month
    total_sum_for_current_month = Orders.calculate_total_sum_for_current_month()
    context = {
        'total_sum': total_sum,
        'average_sum': average_sum,
        'max_sum': max_sum,
        'min_sum': min_sum,
        'total_sum_for_current_month': total_sum_for_current_month
    }
    # orders = Orders.objects.all()

    # fig = px.line(
    #     x=[order.o_date_created for order in orders], 
    #     y=[order.o_sum for order in orders]
    #     )
    # chart = fig.write_html()
    # context1 = {'chart': chart}

    return render(request, 'manager_app/analytics_for_admin.html', context)

def analytics_for_user(request):
    return render(request, 'manager_app/analytics_for_user.html')

# orders_with_shoes_info = Orders.objects.select_related('o_shoes').all()

# for order in orders_with_shoes_info:
#     print("Замовлення ID:", order.id_order)
#     print("Колір взуття:", order.o_shoes.sh_color)
#     print("Модель взуття:", order.o_shoes.sh_model)

@receiver(post_save, sender=Orders)
def update_shoes_count_on_order_create(sender, instance, created, **kwargs):
    if created:
        shoes = instance.o_shoes
        shoes.sh_count -= instance.o_count
        shoes.save()

@receiver(post_save, sender=Reservations)
def update_shoes_count_on_reservation_create(sender, instance, created, **kwargs):
    if created:
        shoes = instance.r_shoes
        shoes.sh_count -= instance.r_count
        shoes.save()



# def analytics_view(request):
#     orders = Orders.objects.all()

#     fig = px.line(
#         x=[order.o_date_created for order in orders], 
#         y=[order.o_sum for order in orders]
#         )
#     chart = fig.show()
#     context = {'chart': chart}
#     return render(request, 'manager_app/analytics.html', context)


# def analytics_view (request):
#     fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
#     fig.show()
#     return render(request, 'manager_app/analytics.html', {'fig': fig})

manager_app/templates/manager_app/items.html
{% extends "manager_app/tables.html" %}
{% load static %}
{% block title %}Items{% endblock %}
{% block table %}
<div class="dropdown-container">
  <button class="dropdown-button main-button">
    <span class="dropdown-title-icon">
      <i class="fa-solid fa-hryvnia-sign"></i>
    </span>
    <span class="dropdown-title text-truncate">UAH</span>
    <span class="dropdown-arrow" style="display: flex; justify-content: center; align-items: center;">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="-3 -3 20 20">
        <path
          d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z" />
      </svg>
    </span>
  </button>
  <div class="dropdown-list-container">
    <div class="dropdown-list-wrapper">
      <ul class="dropdown-list"></ul>
      <!-- <div class="floating-icon" aria-hidden="true"></div> -->
    </div>
  </div>
</div>
<a href="{% url 'manager_add:add-item' %}" class="btn-add-container">+ add item</a>
<thead>
  <tr>
    <th><input type="checkbox" name="headerCheckbox" id="headerCheckbox"></th>
    <th>ID</th>
    <th>Фото</th>
    <th>Назва</th>
    <th>Модель</th>
    <th>Розмір</th>
    <th>Колір</th>
    <th>Кількість</th>
    <th>Виробник</th>
    <th>Вартість</th>
    <th>Управління</th>
  </tr>
</thead>
<tbody>
  {% for item in data %}
  <tr>
    <td><input type="checkbox" name="dataCheckbox" value="{{ item.id }}"></td>
    <td data-id="{{ item.id_shoes }}">{{ item.id_shoes }}</td>
    <td>
      <img src="{{ item.sh_image.url }}" alt="">
    </td>
    <!-- <td><a onclick="openModal() ">{{ item.sh_name }}</a></td> -->
    <td>
      <a href="#" class="open-modal" data-action="{% url 'manager_app:items-photos' item.id_shoes %}" data-id="{{ item.id_shoes }}"
        data-name="{{ item.sh_name }}" data-model="{{ item.sh_model }}" data-size="{{ item.sh_size }}"
        data-color="{{ item.sh_color }}" data-count="{{ item.sh_count }}" data-manufacturer="{{ item.sh_manufacturer }}"
        data-price="{{ item.sh_price }}" onclick="openModal(event); return false;">{{ item.sh_name }}
      </a>
    </td>
    <!-- <td ><span class="item-name">{{ item.sh_name }}</span></td> -->
    <td>{{ item.sh_model }}</td>
    <td>{{ item.sh_size }}</td>
    <td>{{ item.sh_color }}</td>
    <td>{{ item.sh_count }}</td>
    <td>{{ item.sh_manufacturer }}</td>
    <!-- <td>{{ item.sh_price }}</td> -->
    <td> <span class="product-price" data-base-price="{{ item.sh_price }}"><i class="fa-solid fa-hryvnia-sign"></i>{{item.sh_price}}</span> </td>
    <td class="table-controls" style="min-width: 30px">
      <!-- <button class="btn-edit" id="openEditModal"><i class="fa-regular fa-pen-to-square"></i></button> -->
      <div class="btn-edit">
        <a href="{% url 'manager_edit:update-item' item.id_shoes %}">
          <i class="fa-regular fa-pen-to-square"></i>
        </a>
      </div>
      <button class="btn-delete">
        <form action="{% url 'manager_app:items-delete' item.id_shoes %}" method="post">
            {% csrf_token %}
            <button type="submit" style="background:none; border:none; padding:0; margin:0;">
                <i class="fa-solid fa-trash-can"></i>
            </button>
        </form>
    </button>
      <button class="btn-confirm"><i class="fa-regular fa-circle-check"></i></button>
    </td>
  </tr>
  {% endfor %}
</tbody>
{% endblock %}




{% block modals-detailed-view %}

<div id="modal" class="mw-container-item-detail">
  <div class="mw-item-detail-content">
    <!-- <span class="close" onclick="closeModal()">&times;</span> -->
    <a class="close" href="{% url 'manager_app:items' %}">&times;</a>
    <div class="carousel-container">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <img src="{{ item.sh_image.url }}" alt="">
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <div class="mw-di-second-column-container">
      <h1>{{ item.sh_name }}</h1>
      <p>ID: {{ item.id_shoes }}</p>
      <p>Model: {{ item.sh_model }}</p>
      <p>Size: {{ item.sh_size }}</p>
      <p>Color: {{ item.sh_color }}</p>
      <p>Count: {{ item.sh_count }}</p>
      <p>Price: £{{ item.sh_price }}</p>
    </div>
  </div>
</div>

{% endblock %}

manager_app/templates/manager_app/orders.html
{% extends "manager_app/tables.html" %}
{% block title %}Orders{% endblock %}
{% block table %}
<div class="dropdown-container">
    <button class="dropdown-button main-button">
      <span class="dropdown-title-icon">
        <i class="fa-solid fa-hryvnia-sign"></i>
      </span>
      <span class="dropdown-title text-truncate">UAH</span>
      <span class="dropdown-arrow" style="display: flex; justify-content: center; align-items: center;">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="-3 -3 20 20">
          <path
            d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z" />
        </svg>
      </span>
    </button>
    <div class="dropdown-list-container">
      <div class="dropdown-list-wrapper">
        <ul class="dropdown-list"></ul>
        <!-- <div class="floating-icon" aria-hidden="true"></div> -->
      </div>
    </div>
  </div>
    <a href="{% url 'manager_add:add-order' %}" class="btn-add-container">+ add item</a>
    <thead>
        <tr>
            <th>№</th>
            <th>ID Взуття</th>
            <th>Назва</th>
            <th>Колір</th>
            <th>Модель</th>
            <th>Розмір</th>
            <th>Ціна</th>
            <th>Кількість</th>
            <th>Сума</th>
            <th>Отримувач</th>
            <th>Коментар</th>
            <th>Статус</th>
            <th>Керування</th>
        </tr>
    </thead>
    <tbody>
    {% for item in data %}
        <tr>
            <td>{{ item.id_order }}</td>
            <td>{{ item.o_shoes.id_shoes }}</td>
            <td>
                <a 
                href="#" 
                class="open-modal" 
                data-action="{% url 'manager_app:orders-detail' item.o_shoes.id_shoes %}"
                data-id="{{ item.id_order }}" 
                data-name="{{ item.o_shoes.sh_name }}" 
                data-model="{{ item.o_shoes.sh_model }}" 
                data-size="{{ item.o_shoes.sh_size }}" 
                data-color="{{ item.o_shoes.sh_color }}" 
                data-count="{{ item.o_count }}" 
                data-sum="{{ item.order_sum }}"
                data-recipient="{{ item.o_recipient }}"
                data-address="{{ item.o_address }}"
                data-comment="{{item.o_comment}}"
                data-status="{{ item.o_status }}"
                data-username="{{ item.o_user.u_username }}"
                onclick="openModal(event); return false;">{{ item.o_shoes.sh_name }}
              </a>
            </td>
            <td>{{ item.o_shoes.sh_color }}</td>
            <td>{{ item.o_shoes.sh_model }}</td>
            <td>{{ item.o_shoes.sh_size }}</td>
            <td>{{ item.o_shoes.sh_price }}</td>
            <td>{{ item.o_count }}</td>
            <!-- <td>{{ item.order_sum }}</td> -->
            <td><span class="product-price" data-base-price="{{ item.order_sum }}"><i class="fa-solid fa-hryvnia-sign"></i>{{ item.order_sum }}</span></td>
            <td>{{ item.o_recipient }}</td>
            <td>{{ item.o_comment }}</td>
            <td>
                {% if item.o_status == 'accepted' %}
                    <div><span>Прийнято</span></div>
                {% elif item.o_status == 'paid' %}
                    <div><span>Оплачено</span></div>
                {% elif item.o_status == 'in processing' %}
                    <div><span>В обробці</span></div>
                {% elif item.o_status == 'shipped' %}
                    <div><span>Відправлено</span></div>
                {% elif item.o_status == 'delivered' %}
                    <div><span>Доставлено</span></div>
                {% elif item.o_status == 'paid to dropper' %}
                    <div><span>Оплачено поставнику</span></div>
                {% endif %}
            </td>
            <td class="table-controls" style="min-width: 30px">
                <!-- <button onclick="openModalForm(event);return false;" class="btn-edit"><i class="fa-regular fa-pen-to-square"></i></button> -->
                <!-- <button class="btn-edit"><i class="fa-regular fa-pen-to-square"></i></button> -->
                <div class="btn-edit">
                    <a href="{% url 'manager_edit:update-order' item.id_order %}">
                      <i class="fa-regular fa-pen-to-square"></i>
                    </a>
                  </div>
                <button class="btn-delete">
                    <form action="{% url 'manager_app:orders-delete' item.id_order %}" method="post">
                        {% csrf_token %}
                        <button type="submit" style="background:none; border:none; padding:0; margin:0;">
                            <i class="fa-solid fa-trash-can"></i>
                        </button>
                    </form>
                </button>
                <button class="btn-confirm">
                    
                        <button type="submit" style="background: none; border: none;">
                            <i class="fa-regular fa-circle-check"></i>
                        </button>
                    <!-- </form> -->
                </button>
              </td>                

        </tr>
            {% endfor %}
        </tbody>
{% endblock %}

  
{% block modals-detailed-view %}
        
<div id="modal" class="mw-container-item-detail">
  <div class="mw-item-detail-content">
      <span class="close" onclick="closeModal()">&times;</span>
      <div class="carousel-container">
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <img src="{{ item.o_shoes.sh_image.url }}" alt="">
              </div>
              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
              </a>
          </div>
      </div>
      <div class="mw-di-second-column-container">
          <h1>{{ item.o_shoes.sh_name }}</h1>
          <p>ID: {{ item.id_order }}</p>
          <p>Модель: {{ item.o_shoes.sh_model }}</p>
          <p>Розмір {{ item.o_shoes.sh_size }}</p>
          <p>Колір: {{ item.o_shoes.sh_color }}</p>
          <p>Кількість: {{ item.o_shoes.sh_count }}</p>
          <p>Виробник: {{ item.o_shoes.sh_manufacturer }}</p>
          <p>Сума: £{{ item.order_sum }}</p>
          <p>Отримувач: {{ item.o_recipient }}</p>
          <p>Адреса: {{ item.o_address }}</p>
          <p>Коментар: {{ item.o_comment }}</p>
          <p>Користувач: {{ item.o_user.u_username }}</p>
          
      </div>
   </div>
</div>

{% endblock %}