manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('manager_welcome.urls')),
    path('app/', include('manager_app.urls')),
    path('add/', include('manager_add.urls')),
    path('edit/', include('manager_edit.urls')),
    path('authorization/', include('manager_login.urls')),
    path('currency/', include('currency_exchange.urls')),
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager_edit/urls.py
from django.urls import path, include
from . import views

app_name = 'manager_edit'

urlpatterns = [
    # path('', views.index, name='index'),
    path('update_item/<int:shoes_id>/', views.update_item, name='update-item'),
    path('users/update_user/<int:user_id>/', views.update_user, name='update-user'),
    path('orders/update_order/<int:order_id>/', views.update_order, name='update-order'),
    path('reservations/update_reservation/<int:reservation_id>/', views.update_reservation, name='update-reservation'),

    # path('orders/', views.orders, name='orders'),
    # path('reservations/', views.reservations, name='reservations'),
    # path('users/', views.users, name='users'),
    # path('analytics/', views.analytics, name='analytics'),
    # path('convert/<str:currency>/', views.convert_currency, name='convert_currency'),
]

manager_edit/models.py
from django.db import models

# Create your models here.

manager_edit/views.py
from django.shortcuts import render, get_object_or_404, redirect
from manager_app.models import *
from django.contrib import messages


def update_item(request, shoes_id):
    # Отримуємо об'єкт Shoes за його ідентифікатором
    item = get_object_or_404(Shoes, id_shoes=shoes_id)
    if request.method == 'POST':
        item.sh_name = request.POST.get('sh_name')
        item.sh_model = request.POST.get('sh_model')
        item.sh_size = request.POST.get('sh_size')
        item.sh_color = request.POST.get('sh_color')
        item.sh_manufacturer = request.POST.get('sh_manufacturer')
        item.sh_count = request.POST.get('sh_count')
        item.sh_price = request.POST.get('sh_price')
        # item.sh_image = request.POST.get('sh_image')
        # images = request.FILES.getlist('sh_images')
        
        sh_image = request.FILES.get('sh_image')
        if sh_image:
            item.sh_image = sh_image
        item.save()
        return redirect('manager_app:items')
    else:
        return render(request, 'manager_edit/items-edit.html', {'item': item})


def update_user(request, user_id):
    user = get_object_or_404(Users, id_user = user_id)
    
    if request.method == 'POST':
        user.u_username = request.POST.get('u_username')
        user.u_name = request.POST.get('u_name')
        user.u_surname = request.POST.get('u_surname')
        user.u_email = request.POST.get('u_email')
        user.u_phone = request.POST.get('u_phone')
        user.u_status = request.POST.get('u_status') == True
        user.u_role = request.POST.get('u_role')
        user.save()
        return redirect('manager_app:users')
    else:
        user_roles = [(role.value, role.name) for role in User_role]
        return render(request, 'manager_edit/users-edit.html', {'user': user, 'user_roles': user_roles})
    

def update_order(request, order_id):
    order = get_object_or_404(Orders, id_order=order_id)
    shoes_list = Shoes.objects.all()

    if request.method == 'POST':
        o_shoes_id = request.POST.get('o_shoes')
        o_recipient = request.POST.get('o_recipient')
        o_address = request.POST.get('o_address')
        o_comment = request.POST.get('o_comment')
        o_status = request.POST.get('o_status')  # Retrieve o_status from POST data
        o_sum = request.POST.get('o_sum')
        o_user = request.POST.get('o_user')
        
        try:
            shoes = Shoes.objects.get(id_shoes=o_shoes_id)
        except Shoes.DoesNotExist:
            error_message = "Взуття з вказаним ідентифікатором не існує"
            messages.error(request, error_message) 
            return render(request, 'manager_edit/orders-edit.html', {'order': order, 'shoes_list': shoes_list, 'error_message': error_message})
        
        # Перевіряємо, чи кількість взуття більше 0
        if shoes.sh_count > 0:
            # Отримуємо кількість, яку користувач ввів
            o_count = int(request.POST.get('o_count', 0))
           
            # Перевіряємо, чи введена кількість менше або дорівнює кількості в наявності
            if o_count <= shoes.sh_count:
                order.o_shoes = shoes
                order.o_count = o_count
                
                if o_status in [status.value for status in Order_status]:
                    order.o_status = o_status
                    order.o_recipient = o_recipient
                    order.o_address = o_address
                    order.o_comment = o_comment
                    order.save()
                    return redirect('manager_app:orders')
                else:
                    error_message = "Неправильний статус замовлення"
                    messages.error(request, error_message) 
                    return render(request, 'manager_edit/orders-edit.html', {'order': order, 'shoes_list': shoes_list, 'error_message': error_message})
            else:
                error_message = "Вибрана кількість перевищує кількість в наявності"
                messages.error(request, error_message) 
                return render(request, 'manager_edit/orders-edit.html', {'order': order, 'shoes_list': shoes_list, 'error_message': error_message})
        else:
            error_message = "Вибране взуття відсутнє в наявності"
            messages.error(request, error_message) 
            return render(request, 'manager_edit/orders-edit.html', {'order': order, 'shoes_list': shoes_list, 'error_message': error_message})
    else:
        order_status = [(status.value, status.name) for status in Order_status]
        return render(request, 'manager_edit/orders-edit.html', {'order': order, 'shoes_list': shoes_list, 'order_status': order_status})


def update_reservation(request, reservation_id):
    # Отримуємо об'єкт Shoes за його ідентифікатором
    reservation = get_object_or_404(Reservations, id_reservation=reservation_id)
    
    shoes_list = Shoes.objects.all()
    if request.method == 'POST':
        r_shoes_id = request.POST.get('r_shoes')
        try:
            shoes = Shoes.objects.get(id_shoes=r_shoes_id)
        except Shoes.DoesNotExist:
            error_message = "Взуття з вказаним ідентифікатором не існує"
            return render(request, 'manager_edit/reservations-edit.html', {'reservation': reservation, 'error_message': error_message})
        
        # Перевіряємо, чи кількість взуття більше 0
        if shoes.sh_count > 0:
            # Отримуємо кількість, яку користувач ввів
            r_count = int(request.POST.get('r_count', 0))
            
            # Перевіряємо, чи введена кількість менше або дорівнює кількості в наявності
            if r_count <= shoes.sh_count:
                reservation.r_shoes = shoes
                reservation.r_count = r_count
                reservation.save()
                return redirect('manager_app:reservations')
            else:
                error_message = "Вибрана кількість перевищує кількість в наявності"
                return render(request, 'manager_edit/reservations-edit.html', {'reservation': reservation, 'shoes_list': shoes_list, 'error_message': error_message})
        else:
            error_message = "Вибране взуття відсутнє в наявності"
            return render(request, 'manager_edit/reservations-edit.html', {'reservation': reservation,'shoes_list': shoes_list, 'error_message': error_message})
    else:
        return render(request, 'manager_edit/reservations-edit.html', {'reservation': reservation, 'shoes_list': shoes_list})   
   

manager_edit/templates/manager_edit/items-edit.html
{% extends "manager_app/layout.html" %}
{% block content %}
              <div class="form-container">
                <form id="" method="post" enctype="multipart/form-data" action="{% url 'manager_edit:update-item' item.id_shoes %}">
                    {% csrf_token %}
                    <div class="input-and-label-container">
                        <label for="sh_name">Назва взуття:</label>
                        <input type="text" id="sh_name" name="sh_name" value="{{ item.sh_name }}">   
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_model">Модель взуття:</label>
                        <input type="text" id="sh_model" name="sh_model" value="{{ item.sh_model }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_size">Розміри взуття:</label>
                        <input type="number" id="sh_size" name="sh_size" value="{{ item.sh_size }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_color">Колір взуття:</label>
                        <input type="text" id="sh_color" name="sh_color" value="{{ item.sh_color }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_manufacturer">Виробник:</label>
                        <input type="text" id="sh_manufacturer" name="sh_manufacturer" value="{{ item.sh_manufacturer }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_count">Кількість:</label>
                        <input type="number" id="sh_count" name="sh_count" value="{{ item.sh_count }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_price">Ціна:</label>
                        <input type="number" id="sh_price" name="sh_price" value="{{ item.sh_price }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_image">Зображення:</label>
                        <input type="file" id="sh_image" name="sh_image" value="{{ item.sh_image }}">
                    </div>
                    <button type="submit" class="btn">Зберегти</button>
                </form>
            </div>

{% endblock %}

manager_edit/templates/manager_edit/orders-edit.html
{% extends "manager_app/layout.html" %}
{% block content %}
              <div class="form-container">
                <form id="update_ordeo_form" method="post" action="{% url 'manager_edit:update-order' order.id_order %}">
                    {% csrf_token %}
                    <div class="input-and-label-container">
                        <label for="o_shoes">ID взуття:</label>
                        <!-- <input type="number" id="o_shoes" name="o_shoes" value="{% if order.o_shoes %}{{ order.o_shoes.id }}{% endif %}">    -->
                        <select id="o_shoes" name="o_shoes">
                            {% for shoe in shoes_list %}
                                <option value="{{ shoe.id_shoes }}" {% if order.o_shoes.id == shoe.id_shoes %}selected{% endif %}>{{ shoe.id_shoes }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="input-and-label-container">
                        <label for="o_name">Назва:</label>
                        <input type="text" id="o_name" name="o_name" value="{{ order.o_shoes.sh_name }}" disabled>
                    </div>
                    <div class="input-and-label-container">
                        <label for="o_model">Модель:</label>
                        <input type="text" id="o_model" name="o_model" value="{{ order.o_shoes.sh_model }}" disabled>
                    </div>
                    <div class="input-and-label-container">
                        <label for="o_color">Колір:</label>
                        <input type="text" id="o_color" name="o_color" value="{{ order.o_shoes.sh_color }}" disabled>
                    </div>
                    <div class="input-and-label-container">
                        <label for="o_size">Розмір:</label>
                        <input type="number" id="o_size" name="o_size" value="{{ order.o_shoes.sh_size }}" disabled>
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_count">Залишок:</label>
                        <input type="number" id="sh_count" name="sh_count" value="{{ order.o_shoes.sh_count }}" disabled>
                    </div>
                    <div class="input-and-label-container">
                        <label for="o_count">Кількість:</label>
                        <input type="number" id="o_count" name="o_count" value="{{ order.o_count }}" min="1" max="4">
                    </div>
                    <div class="input-and-label-container">
                        <label for="o_recipient">Отримувач:</label>
                        <input type="text" id="o_recipient" name="o_recipient" value="{{ order.o_recipient }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="o_address">Адреса:</label>
                        <input type="text" id="o_address" name="o_address" value="{{ order.o_address }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="o_comment">Коментар:</label>
                        <input type="text" id="o_comment" name="o_comment" value="{{ order.o_comment }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="o_sum">Сума:</label>
                        <input type="number" id="o_sum" name="o_sum" value="{{ order.o_sum }}" disabled>
                    </div>
                    <div class="input-and-label-container">
                        <label for="o_status">Статус:</label>
                        <select id="o_status" name="o_status">
                            {% for value, name in order_status %}
        <option value="{{ value }}" {% if value == order.o_status %} selected {% endif %}>{{ name }}</option>
        {% endfor %}
                        </select>                        
                    </div>
                    <div class="input-and-label-container">
                        <label for="o_user">Сума:</label>
                        <input type="number" id="o_user" name="o_user" value="{{ order.o_sum }}" disabled>
                    </div>
                    <button type="submit" class="btn">Зберегти</button>
                </form>
               </div>
               {% if messages %}
               {% for message in messages %}
                   <div class="alert alert-{{ message.tags }}">{{ message }}</div>
               {% endfor %}
           {% endif %}
{% endblock %}

manager_edit/templates/manager_edit/reservations-edit.html
{% extends "manager_app/layout.html" %}
{% block content %}
              <div class="form-container">
                <form id="update_reservation_form" method="post" action="{% url 'manager_edit:update-reservation' reservation.id_reservation %}">
                    {% csrf_token %}
                    <div class="input-and-label-container">
                        <label for="r_shoes">ID взуття:</label>
                        <!-- <input type="number" id="r_shoes" name="r_shoes" value="{% if reservation.r_shoes %}{{ reservation.r_shoes.id }}{% endif %}">    -->
                        <select id="r_shoes" name="r_shoes">
                            {% for shoe in shoes_list %}
                                <option value="{{ shoe.id_shoes }}" {% if reservation.r_shoes.id == shoe.id_shoes %}selected{% endif %}>{{ shoe.id_shoes }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="input-and-label-container">
                        <label for="r_name">Назва:</label>
                        <input type="text" id="r_name" name="r_name" value="{{ reservation.r_shoes.sh_name }}" disabled>
                    </div>
                    <div class="input-and-label-container">
                        <label for="r_model">Модель:</label>
                        <input type="text" id="r_model" name="r_model" value="{{ reservation.r_shoes.sh_model }}" disabled>
                    </div>
                    <div class="input-and-label-container">
                        <label for="r_color">Колір:</label>
                        <input type="text" id="r_color" name="r_color" value="{{ reservation.r_shoes.sh_color }}" disabled>
                    </div>
                    <div class="input-and-label-container">
                        <label for="r_size">Розмір:</label>
                        <input type="number" id="r_size" name="r_size" value="{{ reservation.r_shoes.sh_size }}" disabled>
                    </div>
                    <div class="input-and-label-container">
                        <label for="r_count">Залишок:</label>
                        <input type="number" id="r_count" name="r_count" value="{{ reservation.r_shoes.sh_count }}" disabled>
                    </div>
                    <div class="input-and-label-container">
                        <label for="r_count">Кількість:</label>
                        <input type="number" id="r_count" name="r_count" value="{{ reservation.r_count }}" min="1" max="4">
                    </div>
                    <button type="submit" class="btn">Зберегти</button>
                </form>
               </div>

{% endblock %}

manager_edit/templates/manager_edit/users-edit.html
{% extends "manager_app/layout.html" %}
{% block content %}
              <div class="form-container">
                <form id="update_ordeo_form" method="post" action="{% url 'manager_edit:update-user' user.id_user %}">
                    {% csrf_token %}
                    <div class="input-and-label-container">
                        <label for="u_username">Ім'я користувача:</label>
                        <input type="text" id="u_username" name="u_username" value="{{ user.u_username }}" >
                    </div>
                    <div class="input-and-label-container">
                        <label for="u_name">Ім'я:</label>
                        <input type="text" id="u_name" name="u_name" value="{{ user.u_name }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="u_surname">Прізвище:</label>
                        <input type="text" id="u_surname" name="u_surname" value="{{ user.u_surname }}" >
                    </div>
                    <div class="input-and-label-container">
                        <label for="u_email">Email:</label>
                        <input type="email" id="u_email" name="u_email" value="{{ user.u_email }}" >
                    </div>
                    <div class="input-and-label-container">
                        <label for="u_phone">Номер телефону:</label>
                        <input type="text" id="u_phone" name="u_phone" value="{{ user.u_phone }}" >
                    </div>
                    <div class="input-and-label-container">
                        <label for="u_role">Роль:</label>
                        <select id="u_role" name="u_role">
                            {% for value, name in user_roles %}
                                <option value="{{ value }}" {% if value == user.u_role %} selected {% endif %}>{{ name }}</option>
                            {% endfor %}
                        </select>                    
                    </div>
                    <div class="input-and-label-container">
                        <label for="u_status">Статус:</label>
                        <input type="checkbox" id="u_status" name="u_status" {% if user.u_status %}checked{% endif %}/>                   
                    </div>
                    <button type="submit" class="btn">Зберегти</button>
                </form>
               </div>
               {% if messages %}
               {% for message in messages %}
                   <div class="alert alert-{{ message.tags }}">{{ message }}</div>
               {% endfor %}
           {% endif %}
{% endblock %}