manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('manager_welcome.urls')),
    path('app/', include('manager_app.urls')),
    path('add/', include('manager_add.urls')),
    path('edit/', include('manager_edit.urls')),
    path('authorization/', include('manager_login.urls')),
    path('currency/', include('currency_exchange.urls')),
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager_add/urls.py
from django.urls import path, include
from . import views

app_name = 'manager_add'

urlpatterns = [
    # path('', views.index, name='index'),
    path('items/add_item/', views.add_item, name='add-item'),
    path('orders/add_order/', views.add_order, name='add-order'),
    path('reservations/add_reservation/', views.add_reservation, name='add-reservation'),
    # path('users/add_user/', views.add_user, name='add-user'),
    # path('orders/add_order/', views.add_order, name='add-order'),
    # path('reservations/add_reservation/', views.add_reservation, name='add-reservation'),

    # path('orders/', views.orders, name='orders'),
    # path('reservations/', views.reservations, name='reservations'),
    # path('users/', views.users, name='users'),
    # path('analytics/', views.analytics, name='analytics'),
    # path('convert/<str:currency>/', views.convert_currency, name='convert_currency'),
]

manager_add/models.py
from django.db import models

# Create your models here.

manager_add/views.py
from django.shortcuts import render, get_object_or_404, redirect
from manager_app.models import *
from django.contrib import messages
from datetime import datetime,timedelta


def add_item(request):

    if request.method == 'POST':
        sh_name = request.POST.get('sh_name')
        sh_model = request.POST.get('sh_model')
        sh_size = request.POST.get('sh_size')
        sh_color = request.POST.get('sh_color')
        sh_manufacturer = request.POST.get('sh_manufacturer')
        sh_count = request.POST.get('sh_count')
        sh_price = request.POST.get('sh_price')
        sh_image = request.FILES.get('sh_image')
            
        Shoes.objects.create(
                sh_name=sh_name,
                sh_model=sh_model,
                sh_size=sh_size,
                sh_color=sh_color,
                sh_manufacturer=sh_manufacturer,
                sh_count=sh_count,
                sh_price=sh_price,
                sh_image=sh_image
            )
        messages.success(request, 'Елемент успішно додано.')
        
        return redirect('manager_app:items')  # Замість 'items' вставте правильну назву вашого URL
    else:
        return render(request, 'manager_add/items-add.html')
    

def add_order(request):
    shoes_list = Shoes.objects.all()
    user_list = Users.objects.all()  # Отримуємо список користувачів
    order_status = [(status.value, status.name) for status in Order_status]

    if request.method == 'POST':
        o_shoes_id = request.POST.get('o_shoes')
        o_recipient = request.POST.get('o_recipient')
        o_address = request.POST.get('o_address')
        o_comment = request.POST.get('o_comment')
        o_status = request.POST.get('o_status')
        o_user_id = request.POST.get('o_user')  # Отримуємо ID користувача
        o_count = int(request.POST.get('o_count', 0))

        shoes = get_object_or_404(Shoes, id_shoes=o_shoes_id)
        user = get_object_or_404(Users, id_user=o_user_id)

        if shoes.sh_count > 0:
            if o_count <= shoes.sh_count:
                if o_status in [status.value for status in Order_status]:
                    o_sum = shoes.sh_price * o_count

                    Orders.objects.create(
                        o_shoes=shoes,
                        o_count=o_count,
                        o_status=o_status,
                        o_recipient=o_recipient,
                        o_address=o_address,
                        o_comment=o_comment,
                        o_sum=o_sum,
                        o_user=user  # Зберігаємо користувача в замовленні
                    )
                    shoes.sh_count -= o_count
                    shoes.save()
                    messages.success(request, 'Замовлення успішно створено.')
                    return redirect('manager_app:orders')
                else:
                    error_message = "Неправильний статус замовлення"
                    messages.error(request, error_message)
            else:
                error_message = "Вибрана кількість перевищує кількість в наявності"
                messages.error(request, error_message)
        else:
            error_message = "Вибране взуття відсутнє в наявності"
            messages.error(request, error_message)
        return render(request, 'manager_add/orders-add.html', {'shoes_list': shoes_list, 'user_list': user_list, 'order_status': order_status, 'error_message': error_message, 'form_data': request.POST})
    else:
        return render(request, 'manager_add/orders-add.html', {'shoes_list': shoes_list, 'user_list': user_list, 'order_status': order_status})


def add_reservation(request):
    shoes_list = Shoes.objects.all()
    user_list = Users.objects.all()  # Отримуємо список користувачів

    if request.method == 'POST':
        r_shoes_id = request.POST.get('r_shoes')
        r_user_id = request.POST.get('r_user')  # Отримуємо ID користувача
        r_count = int(request.POST.get('r_count', 0))

        try:
            shoes = Shoes.objects.get(id_shoes=r_shoes_id)
        except Shoes.DoesNotExist:
            error_message = "Взуття з вказаним ідентифікатором не існує"
            return render(request, 'manager_add/reservations-add.html', {'shoes_list': shoes_list, 'user_list': user_list, 'error_message': error_message, 'form_data': request.POST})
        
        try:
            user = Users.objects.get(id_user=r_user_id)
        except Users.DoesNotExist:
            error_message = "Користувач з вказаним ідентифікатором не існує"
            return render(request, 'manager_add/reservations-add.html', {'shoes_list': shoes_list, 'user_list': user_list, 'error_message': error_message, 'form_data': request.POST})

        if shoes.sh_count > 0:
            if r_count <= shoes.sh_count:
                Reservations.objects.create(
                    r_shoes=shoes,
                    r_count=r_count,
                    r_user=user  # Зберігаємо користувача в резервації
                )
                shoes.sh_count -= r_count
                shoes.save()
                messages.success(request, 'Резервацію успішно створено.')
                return redirect('manager_app:reservations')
            else:
                error_message = "Вибрана кількість перевищує кількість в наявності"
                messages.error(request, error_message)
        else:
            error_message = "Вибране взуття відсутнє в наявності"
            messages.error(request, error_message)
        return render(request, 'manager_add/reservations-add.html', {'shoes_list': shoes_list, 'user_list': user_list, 'error_message': error_message, 'form_data': request.POST})
    else:
        return render(request, 'manager_add/reservations-add.html', {'shoes_list': shoes_list, 'user_list': user_list})

manager_add/templates/manager_add/items-add.html
{% extends "manager_app/layout.html" %}
{% block content %}
              <div class="form-container">
                <form id="" method="post" enctype="multipart/form-data" action="{% url 'manager_add:add-item' %}">
                    {% csrf_token %}
                    <div class="input-and-label-container">                        <label for="sh_name">Назва взуття:</label>
                        <input type="text" id="sh_name" name="sh_name"  value="{{ item.sh_name|default_if_none:'' }}">   
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_model">Модель взуття:</label>
                        <input type="text" id="sh_model" name="sh_model" value="{{ item.sh_model|default_if_none:'' }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_size">Розміри взуття:</label>
                        <input type="number" id="sh_size" name="sh_size" value="{{ item.sh_size|default_if_none:'' }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_color">Колір взуття:</label>
                        <input type="text" id="sh_color" name="sh_color" value="{{ item.sh_color|default_if_none:'' }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_manufacturer">Виробник:</label>
                        <input type="text" id="sh_manufacturer" name="sh_manufacturer" value="{{ item.sh_manufacturer|default_if_none:'' }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_count">Кількість:</label>
                        <input type="number" id="sh_count" name="sh_count" value="{{ item.sh_count|default_if_none:'' }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_price">Ціна:</label>
                        <input type="number" id="sh_price" name="sh_price" value="{{ item.sh_price|default_if_none:'' }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="sh_image">Зображення:</label>
                        <input type="file" id="sh_image" name="sh_image">
                    </div>
                    <button type="submit" class="btn">Зберегти</button>
                </form>
            </div>

{% endblock %}

manager_add/templates/manager_add/orders-add.html
{% extends "manager_app/layout.html" %}
{% block content %}
<div class="form-container">
    <form method="post" enctype="multipart/form-data" action="{% url 'manager_add:add-order' %}">
        {% csrf_token %}
        <div class="input-and-label-container">
            <label for="o_shoes">Взуття:</label>
            <select id="o_shoes" name="o_shoes" required>
                {% for shoe in shoes_list %}
                    <option value="{{ shoe.id_shoes }}" {% if form_data.o_shoes == shoe.id_shoes %}selected{% endif %}>{{ shoe.sh_name }} ({{ shoe.sh_model }}) - {{ shoe.sh_price }} грн</option>
                {% endfor %}
            </select>
        </div>
        <div class="input-and-label-container">
            <label for="o_count">Кількість:</label>
            <input type="number" id="o_count" name="o_count" min="1" required value="{{ form_data.o_count|default_if_none:'' }}">
        </div>
        <div class="input-and-label-container">
            <label for="o_recipient">Одержувач:</label>
            <input type="text" id="o_recipient" name="o_recipient" required value="{{ form_data.o_recipient|default_if_none:'' }}">
        </div>
        <div class="input-and-label-container">
            <label for="o_address">Адреса:</label>
            <input type="text" id="o_address" name="o_address" required value="{{ form_data.o_address|default_if_none:'' }}">
        </div>
        <div class="input-and-label-container">
            <label for="o_comment">Коментар:</label>
            <textarea id="o_comment" name="o_comment">{{ form_data.o_comment|default_if_none:'' }}</textarea>
        </div>
        <div class="input-and-label-container">
            <label for="o_status">Статус:</label>
            <select id="o_status" name="o_status" required>
                {% for value, name in order_status %}
                    <option value="{{ value }}" {% if form_data.o_status == value %}selected{% endif %}>{{ name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="input-and-label-container">
            <label for="o_user">Користувач:</label>
            <select id="o_user" name="o_user" required>
                {% for user in user_list %}
                    <option value="{{ user.id_user }}" {% if form_data.o_user == user.id_user %}selected{% endif %}>{{ user.u_username }}</option>
                {% endfor %}
            </select>        </div>
        <button type="submit" class="btn">Додати замовлення</button>
    </form>

</div>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}" style="color: red;">{{ message }}</div>
{% endfor %}
{% endif %}
{% endblock %}

manager_add/templates/manager_add/reservations-add.html
{% extends "manager_app/layout.html" %}
{% block content %}
              <div class="form-container">
                <form id="update_reservation_form" method="post" action="{% url 'manager_add:add-reservation'  %}">
                    {% csrf_token %}
                    <div class="input-and-label-container">
                        <label for="r_shoes">Взуття:</label>
                        <select id="r_shoes" name="r_shoes" required>
                            {% for shoe in shoes_list %}
                                <option value="{{ shoe.id_shoes }}" {% if form_data.r_shoes == shoe.id_shoes %}selected{% endif %}>{{ shoe.sh_name }} ({{ shoe.sh_model }}) - {{ shoe.sh_price }} грн</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="input-and-label-container">
                        <label for="r_count">Кількість:</label>
                        <input type="number" id="r_count" name="r_count" min="1" required value="{{ form_data.r_count|default_if_none:'' }}">
                    </div>
                    <div class="input-and-label-container">
                        <label for="r_user">Користувач:</label>
                        <select id="r_user" name="r_user" required>
                            {% for user in user_list %}
                                <option value="{{ user.id_user }}" {% if form_data.r_user == user.id_user %}selected{% endif %}>{{ user.u_username }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn">Зберегти</button>
                </form>
               </div>
               {% if error_message %}
               <p style="color: red;">{{ error_message }}</p>
           {% endif %}
{% endblock %}